---
title: "viz_and_eda_09262019"
author: Britney Aazzetta
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library("hexbin")
#install.packages("hexbin")
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## create a ggplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) #Nothing happens w/ this code. We are missing what type of plot R should make. It has only initialized a graph but did not add anything to it

ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()  #Scatterplot
```

Alternate way of making this plot

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
#W/ this code, we are saying 1) start w/ data 2) create the plot (doesnt matter which method we use)
```

saving initial plots. mostly dont use this

```{r}
weather_df %>% filter(name == "CentralPark_NY")

scatterplot = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
#You will only save the plot if you set it equal to something. In this example, we set the plot equal to "scatterplot"
```

adding  color 

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .4)
```

why do 'aes' positions matter?

first
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .4) +
  geom_smooth(se = FALSE)  #geom_smooth adds a line to the graph
```

vs 

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)
```

facet

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE) +
  facet_grid(~name)  #want name to be in the columns
```


this is fine, but not interesting

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE)
```


map of precipitation
```{r}
weather_df %>%
  ggplot(aes(x = date, y = prcp, color = name)) + 
  geom_point() +
  geom_smooth(se = FALSE)
```

```{r}
weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = 0.5) +
  geom_smooth(size = 2, se = FALSE)
```


```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex() #doesnt show every data point, but it shows within density
```

## More kind sof plots

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```

## Hisotgram

```{r}
ggplot(weather_df, aes(x = tmax, color = name)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram()

ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue")
```
```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()
```

violin plots

```{r}
weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()

ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)
```
Ridge Plots

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)

weather_df %>%  #piping - use weather_df in code for ggplot
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```


